name: Update Readme with Coding Activity Chart

on:
  schedule:
    - cron: '0 0 * * *' # run every day at midnight UTC

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install matplotlib
    - name: Generate chart
      run: python generate_chart.py
    - name: Commit chart to repo
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Tobi Olajumoke
        author_email: olajumoketobi01@gmail.com
        message: "Update chart"
        add: 'coding_activity_chart.png'
        push: true
